# Generated by Django 5.2.12 on 2026-03-23 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(choices=[('etoro', 'eToro'), ('xtb', 'XTB')], max_length=20)),
                ('credentials', models.JSONField(blank=True, help_text='Store API keys or tokens. For XTB CSV imports, this can be empty.', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'broker')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('asset_class', models.CharField(blank=True, default='stock', max_length=50)),
                ('quantity', models.FloatField(default=0.0)),
                ('average_open_price', models.FloatField(default=0.0)),
                ('current_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='stocks.brokeraccount')),
            ],
            options={
                'unique_together': {('broker_account', 'symbol')},
            },
        ),
    ]
