# Generated by Django 5.2.12 on 2026-03-23 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_portfolioposition_opened_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField(help_text='Total value of transaction (usually qty * price)')),
                ('date', models.DateTimeField()),
                ('external_id', models.CharField(blank=True, help_text='e.g. Position ID', max_length=100, null=True)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stocks.brokeraccount')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
