# Generated by Django 5.2.12 on 2026-03-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0005_update_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioposition",
            name="total_dividends",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="portfolioposition",
            name="average_open_price",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="portfolioposition",
            name="current_price",
            field=models.DecimalField(
                blank=True, decimal_places=8, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="portfolioposition",
            name="quantity",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=8,
                help_text="Total value of transaction (usually qty * price)",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="quantity",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
